# Config file for automatic testing at travis-ci.org

language: python
sudo: false

addons:
  chrome: "stable"
  firefox: "latest"

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"

firefox:
  - "latest"

chrome:
  - "stable"

matrix:
  allow_failures:
    - python: latest

env:
  global:
    - GECKODRIVER_VERSION=v0.19.1
  matrix:
    - SELENIUM_WEBDRIVER=phantomjs
    - SELENIUM_WEBDRIVER=firefox
    - SELENIUM_WEBDRIVER=chrome

before_install:
  - wget -O - https://github.com/mozilla/geckodriver/releases/download/${GECKODRIVER_VERSION}/geckodriver-${GECKODRIVER_VERSION}-linux64.tar.gz | tar xz
  - wget -O x.zip https://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip && unzip x.zip
  - chmod +x geckodriver chromedriver
  - mkdir ~/drivers/
  - mv geckodriver chromedriver ~/drivers/
  - export PATH=$PATH:~/drivers

install:
  - pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script: python setup.py test

cache:
  - "pip"

#  vim: set ts=2 sw=2 tw=0 et :
