# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"

env:
  - SELENIUM_WEBDRIVER=phantomjs

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements.txt
  - sudo apt-get install phantomjs

# command to run tests, e.g. python setup.py test
script: python setup.py test
